Rm visibility
openEHR/archie pull request #346
Opened 2021-08-23 15:35 UTC by pieterbos

RM Overlay + visibility + alias support.

Done:
- [x] Model implementation
- [x] JAXB + Jackson binding
- [x] ADL parsing and serialization
- [x] added ad-codes as allows archetype nodes, added it to archetype.getAllusedCodes()
- [x] Flattener and OPT-creator 
- [x] Test that parses, validates and flattens and creates and OPT

TODO:
- [ ] test that serializes and parses JSON (odin works, so json should be the same)
- [ ] test that serializes and parses XML
- [ ] test that serializes ADL

2021-08-25 12:58 UTC, pieterbos commented on aom/src/main/java/com/nedap/archie/aom/utils/AOMUtils.java
> +            if(partial.getFoundObjects().isEmpty()) {
hmm, this can't happen since it always returns at least the root node, so this case should probably be removed.

2021-09-02 13:27 UTC, J3173 requested changes

2021-09-02 13:27 UTC, J3173 commented on tools/src/main/java/com/nedap/archie/archetypevalidator/validations/AnnotationsValidation.java
> -    }
Can you also remove the now unused imports?

2021-09-02 13:27 UTC, J3173 commented on tools/src/main/java/com/nedap/archie/archetypevalidator/validations/RmOverlayValidation.java
> +    }
This function is unused.

2021-09-02 13:27 UTC, J3173 commented on tools/src/main/java/com/nedap/archie/archetypevalidator/validations/RmOverlayValidation.java
> +import java.util.Map;
Two of these imports are unused. (And more when the unused function is removed)

2021-09-02 13:34 UTC, pieterbos commented on aom/src/main/java/com/nedap/archie/aom/Archetype.java
> +    //TODO: JAXB type adapter here, this contains just a map
Ah, yes, the TODO is old and needs to go - I will remove it.

2021-09-03 08:53 UTC, pieterbos commented
In the meantime, the ad-code for alias that was already in the standard got replaced by at-codes again. Beter, in my opinion. I will change that with processing review comments and before requesting re-review.

2021-09-03 10:23 UTC, pieterbos commented
comments processed, ad-code replaced with at-code again.

2021-09-03 13:07 UTC, J3173 approved these changes

2021-09-03 14:12 UTC, merged