android fixes for rule evaluation
openEHR/archie pull request #347
Opened 2021-08-27 08:45 UTC by pieterbos

- remove JAXB as a requirement for rules, by replacing path lookup. Did not remove, but deprecated the old path lookup in RuleEvaluation for backwards compatibility.
- Fix a bug in parsing serialized JSON rules
- Fix a integer -> double conversion in rule evaluation that happens only on android so far (??)
- Make terminology service no longer dependent on JAXB, but use jackson instead, so that it works on android
- change epoch for DV_DATE and DV_DATE_TIME magnitude to 1-1-0001, conforming to specs.
- JAXB rule evaluation AssertionsFixer now throws an exception in case there is an XPath syntax error. Should never happen.
New PathQuery lookup does not have this behaviour..

2021-09-02 14:18 UTC, J3173 requested changes

2021-09-02 14:18 UTC, J3173 commented on tools/src/main/java/com/nedap/archie/rules/evaluation/AssertionsFixer.java
>      private void constructMissingStructure(Archetype archetype, String pathOfParent, String lastPathSegment, List<Object> parents) throws XPathExpressionException {
```suggestion
    private void constructMissingStructure(Archetype archetype, String pathOfParent, String lastPathSegment, List<Object> parents) {
```
This doesn't throw XPathExpressionExceptions anymore.

2021-09-03 08:42 UTC, pieterbos commented on openehr-terminology/src/test/java/com/nedap/archie/terminology/OpenEHRTerminologyAccessTest.java
> +        System.out.println(t);
Good idea. Done.

2021-09-03 12:51 UTC, J3173 approved these changes

2021-09-03 12:52 UTC, merged